### PR TITLE
Make oauth2.py compatible with Python 3 and 2.7

### PR DESCRIPTION
**Pull request by micronn**
This is another attempt to make the script compatible with both Python 3 and 2.7. I don't know why the previous pull requests were not merged.

I've done a simple usage tests with both python 2.7.18 and 3.7.7, and they worked well.

### CODE REVIEW

**Comment by haozhou** [comment]
I wonder if anyone has merge permission has plan to merge this PR?

**Comment by davama** [comment]
Just confirming that the changes worked!
Thank you @micronn 

Using Py3.8.3

**Comment by drupol** [comment]
Could be nice to have for FreeBSD !

**Review by arza-zara — APPROVED** [review]

**Comment by junyer** [comment]
Handled in commit 944cffd66df38863eb0252a8096961335e418e70.

**Pull request closed without merging**
