### PR TITLE
Use the XDG config directory by default

### LINKED ISSUE #20: sendgmail go app should respect XDG
Storing the json config in $HOME without respecting a user's configured XDG environment violates the spec.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

### PR DESCRIPTION
**Pull request by favonia**
Completely close #20.

Tagging @jasonkarns in case they have anything to say.

### CODE REVIEW

**Comment by junyer** [comment]
Done in commit 578a11a744c37bd19c1c1b8d96061276dbf6f7f0.

**Comment by junyer** [comment]
`sync.OnceValue()` became available as of Go 1.21 only three months ago, admittedly, but it feels neater than setting a global variable via an `init()` function.

**Comment by favonia** [comment]
@junyer I checked the `sync` package and felt the overhead is quite large---there are mutexes to deal with multithreading and complicated control flows to optimize stack traces. None of these features are useful here. Personally I would suggest using simple boolean values, but I guess it does not hurt much and you are the maintainer. 😅

**Comment by junyer** [comment]
It isn't a hot code path, so what's happening under the hood doesn't hurt at all. It matters more to have clearer, simpler code: the use of `sync.OnceValue()` concisely signals that `isXDG` is a `func() bool` whose return value is memoised.

**Pull request closed without merging**
