### PR TITLE
setup.py: Make this installable as a module.

### PR DESCRIPTION
**Pull request by tripleee**
Provide a simple `setup.py` and empty `__init__.py` to go with it so that you can

```
pip install -e git+https://github.com/google/gmail-oauth2-tools.git#egg=gmail_oauth2_tools&subdirectory=python
```

(Requires pip >= 1.5; see also http://stackoverflow.com/a/26174655/874188)

### CODE REVIEW

**Comment by tripleee** [comment]
Oops, this is not working.  My current guess is that {{pip}} won't cope with the combination of a directory name with dashes in it and having the Python code in a subdirectory.  I'll still try to see if I can come up with a workaround, but this is not finished as it is now.

**Comment by tripleee** [comment]
Confusingly, you have to say `import oauth2` in order to get the library imported.  (This comment replaces an earlier comment where I was speculating about what was wrong, but my speculations seem to have been unfounded.)

**Comment by kootenpv** [comment]
Not really a place to write this, but I was able to "test succesfully" (the test it provides) but afterwards it does not allow me to send a message: `sendmail` does still say it requires authentication.

**Comment by kootenpv** [comment]
import base64
    import smtplib
    
    ### generate access token using script #### 
    
    access_token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    auth_string = 'user=%s\1auth=Bearer %s\1\1' % ("my@gmail.com", access_token)
    
    conn = smtplib.SMTP('smtp.googlemail.com', 587)
    conn.set_debuglevel(True)
    conn.ehlo('test')
    conn.starttls()
    conn.docmd('AUTH', 'XOAUTH2 ' + base64.b64encode(auth_string))
    conn.ehlo('test')
    header = 'To:my@gmail.com\n' + 'From: my@gmail.com\n' + 'Subject:testing \n'
    msg = header + '\n this is test msg from me \n\n'
    conn.sendmail('my@gmail.com', 'my@gmail.com', msg)

**Comment by kootenpv** [comment]
The problem with the example is that the scope cannot be changed from giving all permissions.

**Comment by junyer** [comment]
Sorry, I'm not particularly enthused about making `oauth2.py` installable.

**Pull request closed without merging**
