### PR TITLE
Python3 compatibility update

### PR DESCRIPTION
**Pull request by bazz1tv**
Dear Google,

These changes allow the python oauth2 tool to run on both python2 and python3.

I've done the following testing manually on python2.7 and python3.6
* --generate_oauth2_token OK
* --test_imap_authentication OK
* --test_smtp_authentication OK
* generate new access tokens from refresh token OK

### CODE REVIEW

**Comment by bazzinotti** [comment]
I signed the CLA! :dancer:

**Comment by modernNeo** [comment]
can this pull request please be merged? I need the script to work with python3 for a site I am working on. Thanks

**Comment by the0neWhoKnocks** [comment]
There are multiple PRs to patch this script for Python3, and this is the only one that worked for me because it took into account for the JSON response coming back as bytes and actually `decode`d it before trying to parse it.
```python
return json.loads(response.decode())
```
👍

**Comment by junyer** [comment]
Handled in commit 944cffd66df38863eb0252a8096961335e418e70.

**Pull request closed without merging**
